# Generated by Django 3.0.5 on 2020-06-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='threadid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='DropBag.Thread'),
        ),
        migrations.AddField(
            model_name='post',
            name='threadid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='DropBag.Thread'),
        ),
    ]
