# Generated by Django 3.0.5 on 2020-07-19 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thread_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_subscribe', to='DropBag.Thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'thread')},
            },
        ),
    ]
