# Generated by Django 3.0.5 on 2020-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0002_thread_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
