# Generated by Django 3.0.5 on 2020-07-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0004_auto_20200720_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
