# Generated by Django 3.0.5 on 2020-07-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0004_auto_20200710_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parentid',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='threadid',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='userid',
            new_name='user',
        ),
    ]
