# Generated by Django 3.0.5 on 2020-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0005_auto_20200721_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.TimeField(blank=True),
        ),
    ]
