# Generated by Django 3.0.5 on 2020-07-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0008_auto_20200724_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'post')},
        ),
    ]
