# Generated by Django 3.0.5 on 2020-07-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0009_auto_20200724_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='vote',
            new_name='score',
        ),
    ]
