# Generated by Django 3.0.5 on 2020-07-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DropBag', '0011_auto_20200725_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'post', 'comment')},
        ),
    ]
